### ISSUE TITLE
clang-format should be installed on the VM

### ISSUE THREAD

**Issue by orenht** [Cyanivde/technion-project-setup#3]
The installation of the clang-format VS code extension is not installing the clang format executable on the remote VM, and then the formatter on VS code fails with an error.

Running `sudo apt install clang-format` is not good enough, since the default clang-format version (6) on ubuntu 18 is very old and does not support new flags such as `BasedOnStyle: Microsoft` you have in your .clang-format file :)

Following [this answer](https://stackoverflow.com/questions/20756924/how-can-i-install-clang-format-in-ubuntu/66654073#66654073) helped me install it on the VM. I installed version 12 and it works successfully.

**Comment by Cyanivde** [comment]
Hi, thanks for writing!
Note the guide suggest installing clang-format-10 rather than the default version (6). 
It's not the latest version but I think it's better to keep it simple... what do you think?

**Comment by orenht** [comment]
Oops, you're right!
I think my actual problem was that the installation didn't create a link to `clang-format` (only `clang-format-10` was in the PATH), and the default value of the setting Clang-format: executable was `clang-format` without the version number.
That's why I thought it didn't get installed. 

Did this happen in your machine too? maybe the setting should be changed manually

**Comment by Cyanivde** [comment]
I think it has and that I fixed it without writing it down. Updating now, thanks!
